'use client';

import { SOURCES } from '@/lib/sources';
import Link from 'next/link';

export default function SourcesPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-mist-400 via-mist-50 to-mist-400 p-8">
      <div className="max-w-3xl mx-auto">
        {/* was /presentationv2: the canvas page is the main lesson now */}
        <Link href="/presentation" className="text-blue-600 hover:underline text-sm">
          ← Back to the lesson
        </Link>

        <h1 className="text-4xl font-bold text-black mt-6 mb-2">Sources</h1>
        <p className="text-blue-700 mb-10">
          Everything in this lesson is drawn from these publicly available resources.
        </p>

        <div className="space-y-4">
          {SOURCES.map((s, i) => (
            <a
              key={i}
              href={s.url}
              target="_blank"
              rel="noopener noreferrer"
              className="block bg-white/60 hover:bg-white rounded-2xl border border-blue-200 hover:border-blue-400 p-5 transition-colors"
            >
              <div className="font-semibold text-blue-900">{s.title}</div>
              <div className="text-sm text-slate-600 mt-1">{s.org}</div>
            </a>
          ))}
        </div>

        <p className="text-slate-500 text-sm mt-10">
          Lesson content is generated by AI from these sources. Images and narration are
          produced automatically and may contain errors — always check the originals.
        </p>
      </div>
    </div>
  );
}
