'use client';
import Link from 'next/link';

const SOURCES = [
  {
    title: "Chesapeake Bay Blue Catfish: Invasive, but Delicious and Nutritious! (FS-1142)",
    org: "University of Maryland Extension",
    url: "https://extension.umd.edu/resource/chesapeake-bay-blue-catfish-invasive-delicious-and-nutritious-fs-1142",
  },
  {
    title: "Blue Catfish",
    org: "Maryland Department of Natural Resources",
    url: "https://dnr.maryland.gov/fisheries/Pages/blue-catfish/blue_catfish_main.aspx",
  },
  {
    title: "Understanding the Chesapeake's catfish problem",
    org: "Chesapeake Bay Program",
    url: "https://www.chesapeakebay.net/news/blog/understanding-the-chesapeakes-catfish-problem",
  },
  {
    title: "Blue Catfish",
    org: "NOAA Fisheries",
    url: "https://www.fisheries.noaa.gov/species/blue-catfish",
  },
  {
    title: "Blue Catfish: Invasive and Delicious",
    org: "NOAA Fisheries",
    url: "https://www.fisheries.noaa.gov/feature-story/blue-catfish-invasive-and-delicious",
  },
  {
    title: "Blue Catfish — Field Guide",
    org: "Chesapeake Bay Program",
    url: "https://www.chesapeakebay.net/discover/field-guide/entry/blue-catfish",
  },
];

export default function SourcesPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-mist-400 via-mist-50 to-mist-400 p-8">
      <div className="max-w-3xl mx-auto">
        <Link href="/presentationv2" className="text-blue-600 hover:underline text-sm">
          ← Back to the lesson
        </Link>

        <h1 className="text-4xl font-bold text-black mt-6 mb-2">Sources</h1>
        <p className="text-blue-700 mb-10">
          Everything in this lesson is drawn from these publicly available resources.
        </p>

        <div className="space-y-4">
          {SOURCES.map((s, i) => (
            <a
              key={i}
              href={s.url}
              target="_blank"
              rel="noopener noreferrer"
              className="block bg-white/60 hover:bg-white rounded-2xl border border-blue-200 hover:border-blue-400 p-5 transition-colors"
            >
              <div className="font-semibold text-blue-900">{s.title}</div>
              <div className="text-sm text-slate-600 mt-1">{s.org}</div>
            </a>
          ))}
        </div>

        <p className="text-slate-500 text-sm mt-10">
          Lesson content is generated by AI from these sources. Images and narration are
          produced automatically and may contain errors — always check the originals.
        </p>
      </div>
    </div>
  );
}
